### ISSUE TITLE
Update PR template to add check item to update requirement.txt (if needed)

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#56]
## Description
As a developer,
I need to update the requirements.txt every time I use a new package,
so that I can install all the correct packages to work with the backend.

**Task:** Add check item to Pull Request template checklist, so that the requirements.txt is always updated when needed.

### Update
- [x] Update PR template with new check item

## Definition of Done
- [x] All of the required items are completed.
- [x] Submit PR to `develop` branch.
- [x] Approval by 1 mentor.

## Estimation
30 minutes
